MinGW: Fix build with headerclean check
qaxtypefunctions.h uses IUnknown as base class, which
causes warnings on MinGW due to not having a virtual
destructor:

qaxtypefunctions.h:57:8: error: base class 'struct IUnknown' has accessible non-virtual destructor [-Werror=non-virtual-dtor]
 struct IAxServerBase : public IUnknown

QAxFactory hides the declaration of metaObject() in QObject:

qobjectdefs.h:158:32: error: 'virtual const QMetaObject* QObject::metaObject() const' was hidden [-Werror=overloaded-virtual]
     virtual const QMetaObject *metaObject() const; \
                                ^
qaxfactory.h:68:32: error:   by 'virtual const QMetaObject*
QAxFactory::metaObject(const QString&) const' [-Werror=overloaded-virtual]
     virtual const QMetaObject *metaObject(const QString &key) const = 0;
                                ^

Task-number: QTBUG-45666
Change-Id: I9cdf275a1c74950d66c19e025918b8416f94d9ca
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@theqtcompany.com>
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@theqtcompany.com>